from __future__ import annotations

import unittest

from stagewarden.json_schema_registry import JSON_SCHEMA_REGISTRY, JSON_SCHEMA_VERSION, json_schema, json_schema_commands


class JsonSchemaRegistryTests(unittest.TestCase):
    def test_json_schema_registry_covers_operational_views(self) -> None:
        expected = {
            "status",
            "statusline",
            "commands",
            "slash",
            "slash choose",
            "baseline",
            "battery",
            "shell backend",
            "auth status",
            "project brief",
            "project brief set",
            "project brief clear",
            "project design",
            "project tree propose",
            "project tree approve",
            "overview",
            "health",
            "preflight",
            "report",
            "handoff",
            "boundary",
            "board",
            "doctor",
            "models",
            "model",
            "model inspect",
            "model limits",
            "model limit-record",
            "model limit-clear",
            "account limit-record",
            "account limit-clear",
            "file",
            "catalog status",
            "catalog search",
            "catalog",
            "catalog refresh",
            "goal",
            "goal set",
            "goal status",
            "goal clear",
            "goal loop",
            "goal loop run",
            "goal loop status",
            "goal loop add-node",
            "goal loop custom-nodes",
            "budget",
            "budget set",
            "budget status",
            "budget clear",
            "question",
            "question ask",
            "answer",
            "rag",
            "rag benchmark",
            "help",
            "accounts",
            "permissions",
            "roles",
            "roles domains",
            "roles tree",
            "roles tree approve",
            "roles baseline",
            "roles baseline matrix",
            "roles context",
            "roles active",
            "roles control",
            "roles queues",
            "roles messages",
            "roles runtime",
            "roles tick",
            "roles check",
            "roles flow",
            "roles matrix",
            "sources status",
            "sources update",
            "update",
            "update status",
            "update check",
            "update apply",
            "extensions",
            "file inspect",
            "file stat",
            "file copy",
            "file move",
            "file delete",
            "file chmod",
            "file chown",
            "shell backend use",
            "web search",
            "download",
            "checksum",
            "hash",
            "compress",
            "archive verify",
            "archive list",
            "archive extract",
            "archive create",
            "browser fetch",
            "browser open",
            "browser screenshot",
            "watch",
            "system info",
            "disk usage",
            "process list",
            "process kill",
            "port check",
            "clipboard get",
            "clipboard set",
            "clipboard clear",
            "open url",
            "git",
            "external_io",
            "git status",
            "git log",
            "git history",
            "git show",
            "sessions",
            "risks",
            "issues",
            "quality",
            "exception",
            "lessons",
            "todo",
            "transcript",
            "resume --show",
            "resume context",
            "resume --clear",
            "models usage",
            "provider limits",
            "ljson benchmark",
            "openrouter benchmark",
            "prince2 benchmark",
        }
        self.assertEqual(set(json_schema_commands()), expected)
        self.assertEqual(set(JSON_SCHEMA_REGISTRY), expected)

    def test_json_schema_registry_uses_shared_version(self) -> None:
        for command in json_schema_commands():
            payload = json_schema(command)
            self.assertEqual(payload["name"], JSON_SCHEMA_REGISTRY[command])
            self.assertEqual(payload["version"], JSON_SCHEMA_VERSION)


if __name__ == "__main__":
    unittest.main()
